---
title: '2020-11-18'
author: "Grace"
date: "2020/11/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
df_example <- as.data.frame(example)
```

```{r}
tr_example <- purrr::transpose(example)
str(tr_example)
```

```{r}
# 使用list的工具
df_example$name[c(1,4)]

# 使用data frame的延伸工具`[.row, .column]`
df_example[c(1,4), "name"]
df_example[c(1,4),1]
df_example[c(1,4),c(T,rep(F,7))]
#rep(什麼東西，要重複幾次)

#取小明的特徵
df_example[c(1),1:8]#1:8 就是一到八直行
View(df_example[1, ])#去看一下其架構
df_example[1, ]$hobby#$取完就是值，不會有母層的代號
df_example[1, ][[5]]#和下面是不一樣的，他是個character
df_example[1, ][5]#取出來的是data frame
```



